admin = "Admin"
blog = "Blog"
create = "Create"
create_blog_post = "Create Blog Post"
create_tournament = "Create Tournament"
created_by = "Created by"
dashboard = "Dashboard"
easy_to_create_tournaments = "Easy to create tournaments"
email = "Email"
fork_this_project_on = "Fork this project on"
home = "Home"
login = "Login"
logout = "Logout"
no_spam_notice = "If you want to receive updates from us just pop your email in the box. We think that spam is for jerks. And jerks we are not."
optional = "Optional"
privacy_policy = "Privacy Policy"
register = "Register"
search = "Search"
site_name = "Tournify.io"
site_name_first = "Tournify"
site_name_last = ".io"
subscribe = "Subscribe"
subscribe_to_our_newsletter = "Subscribe to our newsletter"
terms_of_service = "Terms of Service"
tournament_name = "Tournament name"
