activate_title = "Activate"
admin = "Admin"
admin_title = "Admin"
ago = "ago"
all_rights_reserved = "All rights reserved."
blog = "Blog"
create = "Create"
create_blog_post = "Create Blog Post"
create_tournament = "Create Tournament"
create_tournament_title = "Create Tournament"
created_by = "Created by"
dashboard = "Dashboard"
easy_to_create_tournaments = "Easy to create tournaments"
email = "Email"
forgot_password_title = "Forgot Password"
fork_this_project_on = "Fork this project on"
home = "Home"
login = "Login"
login_title = "Login"
logout = "Logout"
no_spam_notice = "If you want to receive updates from us just pop your email in the box. We think that spam is for jerks. And jerks we are not."
not_found_title = "404 Not Found"
optional = "Optional"
privacy_policy = "Privacy Policy"
privacy_policy_title = "Privacy Policy"
recent_tournaments = "Recent Tournaments"
register = "Register"
register_title = "Register"
resend_activation_email_title = "Resend Activation Email"
reset_password_title = "Reset Password"
search = "Search"
search_title = "Search"
site_name = "Tournify.io"
site_name_first = "Tournify"
site_name_last = ".io"
subscribe = "Subscribe"
subscribe_to_our_newsletter = "Subscribe to our newsletter"
terms_of_service = "Terms of Service"
terms_of_service_title = "Terms of Service"
the_tournament = "The tournament"
tournament_name = "Tournament Name"
tournament_title = "Tournament"
was_created = "was created"
