16th_final = "16th-Final"
32nd_final = "32nd-Final"
404_notice_about_old_website = "We recently created a new website, if you are looking for an old tournament please go to https://old.tournify.io"
activate_title = "Activate"
admin = "Admin"
admin_title = "Admin"
advanced = "Advanced"
ago = "ago"
all_rights_reserved = "All rights reserved."
and = "and"
away_team = "Away Team"
blog = "Blog"
click_here = "Click here"
coming_soon = "coming soon"
cookie_login_text = "By pressing the button below to login you agree to the use of cookies on this website."
create = "Create"
create_blog_post = "Create Blog Post"
create_tournament = "Create Tournament"
create_tournament_title = "Create Tournament"
created_by = "Created by"
dashboard = "Dashboard"
diff = "Diff"
easy_to_create_tournaments = "Easy to create tournaments"
eight_final = "Eight-Final"
elimination = "Elimination"
elimination_count = "How many teams are eliminated from each group?"
email = "Email"
email_address = "Email address"
enter_new_password = "Please enter a new password."
final = "Final"
forgot_password = "Forgot password?"
forgot_password_text = "Use the form below to reset your password. If we have an account with your email you will receive instructions on how to reset your passsword."
forgot_password_title = "Forgot Password"
fork_this_project_on = "Fork this project on"
game = "Game"
games = "Games"
group = "Group"
home = "Home"
home_team = "Home Team"
login = "Login"
login_title = "Login"
logout = "Logout"
lost = "Lost"
mix_teams = "Mix teams"
name = "Name"
no_spam_notice = "If you want to receive updates from us just pop your email in the box. We think that spam is for jerks. And jerks we are not."
not_found_text = "The page you're looking for could not be found."
not_found_title = "404 Not Found"
number_of_groups = "Number of groups"
number_of_meets = "How many times should every team meet?"
number_of_teams = "Number of teams (Max 64)"
optional = "Optional"
password = "Password"
played = "Played"
points = "Points"
points_for_draw = "Points for a draw"
points_for_loss = "Points for losing"
points_for_winning = "Points for winning"
privacy_policy = "Privacy Policy"
privacy_policy_part_1 = "Names of games, teams, players, your account and related info for public tournaments are public and can be shown on the website. Tournaments which are private or only accessible via link are only shown to users who have been granted access or use the link."
privacy_policy_part_2 = "We will not share your email with third parties and we will not use it to send out advertising not related to our website or company. You may unsubscribe or ask to have your email removed at anytime. The email may be kept if you have made financial transactions with us."
privacy_policy_part_3 = "We use cookies to allow users to create tournaments and log in to our website."
privacy_policy_title = "Privacy Policy"
private = "Private"
public = "Public"
quarter_final = "Quarter-Final"
recent_tournaments = "Recent Tournaments"
register = "Register"
register_agree = "By registering you agree to our"
register_title = "Register"
request_activation_email = "Request a new activation email"
request_reset_email = "Request reset email"
resend_activation_email = "Resend Activation Email"
resend_activation_email_text = "If you have already registered but never activated your account you can use the form below to request a new activation email."
resend_activation_email_title = "Resend Activation Email"
reset_password_title = "Reset Password"
return_to_main = "to return to the main page."
search = "Search"
search_results = "Search Results"
search_title = "Search"
semi_final = "Semi-Final"
site_name = "Tournify.io"
site_name_first = "Tournify"
site_name_last = ".io"
subscribe = "Subscribe"
subscribe_to_our_newsletter = "Subscribe to our newsletter"
team = "Team"
terms_of_service = "Terms of Service"
terms_of_service_part_1 = "We try to make our terms of service easy to read. Don't abuse our site by using foul language or any other kind of abuse. Your account and any content on the site can be deleted at anytime. These terms may change at any time without notice."
terms_of_service_part_2 = "We are not responsible for the content posted by users. Please send an email to markus@tournify.io regarding take downs and we will do our best to respond within 24 hours."
terms_of_service_part_3 = "Please see our privacy policy if you want to know what we do with your information."
terms_of_service_title = "Terms of Service"
the_tournament = "The tournament"
ties = "Ties"
tournament_create_text = "By clicking create you agree to the use of cookies on this website. Please note that it may take a moment to generate the tournament after clicking create."
tournament_name = "Tournament Name"
tournament_title = "Tournament"
type = "Type"
under_construction_text = "Page is under construction"
view_tournament = "View Tournament"
visibility = "Visibility"
visible_with_link = "Visible with link"
was_created = "was created"
wins = "Wins"
