services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tournify
      MYSQL_DATABASE: tournify
      MYSQL_USER: tournify
      MYSQL_PASSWORD: tournify
    ports:
      - "3306:3306"
  tournify:
    build: .
    container_name: tournify
    environment:
      - PORT=:80
      - BASE_URL=http://localhost:8080
      - COOKIE_SECRET=
      - DATABASE=mysql
      - DATABASE_NAME=tournify
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=tournify
      - DATABASE_PASSWORD=tournify
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_SENDER=
      - STRICT_TRANSPORT_SECURITY=false
      - REQUESTS_PER_MINUTE=5
      - CACHE_PARAMETER=
      - ADMIN_EMAIL=
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db_data: {}
